services:
  - type: web
    name: tidescore
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SUPABASE_URL
        fromSecret: SUPABASE_URL
      - key: SUPABASE_KEY  
        fromSecret: SUPABASE_KEY
      - key: DATA_DIR
        value: /tmp/data  # This directory persists across deploys
      - key: ADMIN_PASSWORD  # ← ADD THIS
        fromSecret: ADMIN_PASSWORD  # ← ADD THIS (set in Render dashboard)